const weatherCodes = {
  0: 'ciel dégagé',
  1: 'ciel pluôt dégagé',
  2: 'ciel partiellement nuageux',
  3: 'ciel couvert',
  45: 'brouillard',
  48: 'brouillard givrant',
  51: 'légère bruine',
  53: 'bruine',
  55: 'bruine dense',
  56: 'bruine verglaçante de faible intensité',
  57: 'bruine verglaçante de forte intensité',
  61: 'légère pluie',
  63: 'pluie modérée',
  65: 'forte pluie',
  66: 'pluies verglaçantes de faible intensité',
  67: 'pluies verglaçantes de forte intensité',
  71: 'légères chutes de neige',
  73: 'chutes de neige',
  75: 'fortes chutes de neige',
  77: 'grèle',
  80: 'averses légères',
  81: 'averses modérées',
  82: 'fortes averses',
  85: 'averses de neige légères',
  86: 'fortes averses légères',
  95: 'orages',
  96: 'orages avec chutes de grèle de faible intensité',
  99: 'orages avec chutes de grèle de forte intensité'
}

module.exports = weatherCodes